[2025-01-17T05:35:08.540+0000] {processor.py:186} INFO - Started process (PID=181) to work on /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T05:35:08.662+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/monthly_dependancy.py for tasks to queue
[2025-01-17T05:35:09.278+0000] {logging_mixin.py:190} INFO - [2025-01-17T05:35:09.219+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T05:35:10.930+0000] {processor.py:925} INFO - DAG(s) 'monthly_dag' retrieved from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T05:35:19.351+0000] {logging_mixin.py:190} INFO - [2025-01-17T05:35:19.326+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:monthly_dag
[2025-01-17T05:35:19.573+0000] {logging_mixin.py:190} INFO - [2025-01-17T05:35:19.567+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:monthly_dag
[2025-01-17T05:35:19.711+0000] {logging_mixin.py:190} INFO - [2025-01-17T05:35:19.709+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:monthly_dag
[2025-01-17T05:35:19.807+0000] {logging_mixin.py:190} INFO - [2025-01-17T05:35:19.801+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:monthly_dag
[2025-01-17T05:35:19.898+0000] {logging_mixin.py:190} INFO - [2025-01-17T05:35:19.897+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:monthly_dag
[2025-01-17T05:35:20.015+0000] {logging_mixin.py:190} INFO - [2025-01-17T05:35:20.015+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:monthly_dag
[2025-01-17T05:35:20.124+0000] {logging_mixin.py:190} INFO - [2025-01-17T05:35:20.110+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:monthly_dag
[2025-01-17T05:35:20.162+0000] {logging_mixin.py:190} INFO - [2025-01-17T05:35:20.159+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-17T05:35:21.217+0000] {logging_mixin.py:190} INFO - [2025-01-17T05:35:21.215+0000] {dag.py:3262} INFO - Creating ORM DAG for monthly_dag
[2025-01-17T05:35:21.918+0000] {logging_mixin.py:190} INFO - [2025-01-17T05:35:21.898+0000] {dag.py:4180} INFO - Setting next_dagrun for monthly_dag to 2024-12-01 00:00:00+00:00, run_after=2025-01-01 00:00:00+00:00
[2025-01-17T05:35:22.785+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/monthly_dependancy.py took 15.174 seconds
[2025-01-17T05:35:54.171+0000] {processor.py:186} INFO - Started process (PID=205) to work on /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T05:35:54.274+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/monthly_dependancy.py for tasks to queue
[2025-01-17T05:35:54.666+0000] {logging_mixin.py:190} INFO - [2025-01-17T05:35:54.604+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T05:35:55.489+0000] {processor.py:925} INFO - DAG(s) 'monthly_dag' retrieved from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T05:35:56.704+0000] {logging_mixin.py:190} INFO - [2025-01-17T05:35:56.704+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-17T05:35:56.995+0000] {logging_mixin.py:190} INFO - [2025-01-17T05:35:56.994+0000] {dag.py:4180} INFO - Setting next_dagrun for monthly_dag to 2024-12-01 00:00:00+00:00, run_after=2025-01-01 00:00:00+00:00
[2025-01-17T05:35:57.212+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/monthly_dependancy.py took 3.485 seconds
[2025-01-17T05:36:27.981+0000] {processor.py:186} INFO - Started process (PID=222) to work on /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T05:36:27.986+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/monthly_dependancy.py for tasks to queue
[2025-01-17T05:36:28.073+0000] {logging_mixin.py:190} INFO - [2025-01-17T05:36:28.066+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T05:36:28.458+0000] {processor.py:925} INFO - DAG(s) 'monthly_dag' retrieved from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T05:36:28.789+0000] {logging_mixin.py:190} INFO - [2025-01-17T05:36:28.788+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-17T05:36:29.045+0000] {logging_mixin.py:190} INFO - [2025-01-17T05:36:29.040+0000] {dag.py:4180} INFO - Setting next_dagrun for monthly_dag to 2024-12-01 00:00:00+00:00, run_after=2025-01-01 00:00:00+00:00
[2025-01-17T05:36:29.166+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/monthly_dependancy.py took 1.319 seconds
[2025-01-17T05:38:44.367+0000] {processor.py:186} INFO - Started process (PID=237) to work on /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T05:38:44.429+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/monthly_dependancy.py for tasks to queue
[2025-01-17T05:38:45.310+0000] {logging_mixin.py:190} INFO - [2025-01-17T05:38:45.258+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T05:38:51.474+0000] {processor.py:925} INFO - DAG(s) 'monthly_dag' retrieved from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T05:40:58.470+0000] {processor.py:211} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 207, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 188, in _handle_dag_file_processing
    result: tuple[int, int, int] = dag_file_processor.process_file(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 942, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 982, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 708, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 721, in _sync_to_db
    _serialize_dag_capturing_errors(dag, session, processor_subdir)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 686, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/serialized_dag.py", line 160, in write_dag
    if session.scalar(
       ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-01-17T05:47:08.724+0000] {processor.py:186} INFO - Started process (PID=258) to work on /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T05:47:08.818+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/monthly_dependancy.py for tasks to queue
[2025-01-17T05:47:09.119+0000] {logging_mixin.py:190} INFO - [2025-01-17T05:47:09.012+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T05:47:16.334+0000] {processor.py:925} INFO - DAG(s) 'monthly_dag' retrieved from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T05:48:13.488+0000] {processor.py:211} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 207, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 188, in _handle_dag_file_processing
    result: tuple[int, int, int] = dag_file_processor.process_file(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 942, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 982, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 708, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 721, in _sync_to_db
    _serialize_dag_capturing_errors(dag, session, processor_subdir)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 686, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/serialized_dag.py", line 160, in write_dag
    if session.scalar(
       ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-01-17T05:56:08.548+0000] {processor.py:186} INFO - Started process (PID=283) to work on /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T05:56:09.564+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/monthly_dependancy.py for tasks to queue
[2025-01-17T05:56:10.039+0000] {logging_mixin.py:190} INFO - [2025-01-17T05:56:09.797+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T05:56:13.505+0000] {processor.py:925} INFO - DAG(s) 'monthly_dag' retrieved from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T06:04:02.071+0000] {processor.py:186} INFO - Started process (PID=322) to work on /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T06:04:02.108+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/monthly_dependancy.py for tasks to queue
[2025-01-17T06:04:02.866+0000] {logging_mixin.py:190} INFO - [2025-01-17T06:04:02.797+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T06:04:04.010+0000] {processor.py:925} INFO - DAG(s) 'monthly_dag' retrieved from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T06:20:40.368+0000] {processor.py:186} INFO - Started process (PID=386) to work on /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T06:20:40.372+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/monthly_dependancy.py for tasks to queue
[2025-01-17T06:20:40.380+0000] {logging_mixin.py:190} INFO - [2025-01-17T06:20:40.379+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T06:20:40.422+0000] {processor.py:925} INFO - DAG(s) 'monthly_dag' retrieved from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T06:20:41.195+0000] {logging_mixin.py:190} INFO - [2025-01-17T06:20:41.194+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-17T06:20:41.264+0000] {logging_mixin.py:190} INFO - [2025-01-17T06:20:41.263+0000] {dag.py:4180} INFO - Setting next_dagrun for monthly_dag to 2024-12-01 00:00:00+00:00, run_after=2025-01-01 00:00:00+00:00
[2025-01-17T06:20:41.525+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/monthly_dependancy.py took 1.175 seconds
[2025-01-17T06:21:12.257+0000] {processor.py:186} INFO - Started process (PID=403) to work on /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T06:21:12.259+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/monthly_dependancy.py for tasks to queue
[2025-01-17T06:21:12.266+0000] {logging_mixin.py:190} INFO - [2025-01-17T06:21:12.265+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T06:21:12.319+0000] {processor.py:925} INFO - DAG(s) 'monthly_dag' retrieved from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T06:21:12.385+0000] {logging_mixin.py:190} INFO - [2025-01-17T06:21:12.385+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-17T06:21:12.448+0000] {logging_mixin.py:190} INFO - [2025-01-17T06:21:12.447+0000] {dag.py:4180} INFO - Setting next_dagrun for monthly_dag to 2024-12-01 00:00:00+00:00, run_after=2025-01-01 00:00:00+00:00
[2025-01-17T06:21:12.504+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/monthly_dependancy.py took 0.263 seconds
[2025-01-17T06:27:58.386+0000] {processor.py:186} INFO - Started process (PID=435) to work on /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T06:27:59.427+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/monthly_dependancy.py for tasks to queue
[2025-01-17T06:27:59.782+0000] {logging_mixin.py:190} INFO - [2025-01-17T06:27:59.648+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T06:28:03.917+0000] {processor.py:925} INFO - DAG(s) 'monthly_dag' retrieved from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T06:46:22.258+0000] {processor.py:186} INFO - Started process (PID=498) to work on /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T06:46:22.338+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/monthly_dependancy.py for tasks to queue
[2025-01-17T06:46:22.521+0000] {logging_mixin.py:190} INFO - [2025-01-17T06:46:22.468+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T06:46:26.733+0000] {processor.py:925} INFO - DAG(s) 'monthly_dag' retrieved from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T06:57:43.630+0000] {processor.py:186} INFO - Started process (PID=540) to work on /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T06:57:43.640+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/monthly_dependancy.py for tasks to queue
[2025-01-17T06:57:43.670+0000] {logging_mixin.py:190} INFO - [2025-01-17T06:57:43.669+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T06:57:43.776+0000] {processor.py:925} INFO - DAG(s) 'monthly_dag' retrieved from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T06:57:44.923+0000] {logging_mixin.py:190} INFO - [2025-01-17T06:57:44.918+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-17T06:57:45.332+0000] {logging_mixin.py:190} INFO - [2025-01-17T06:57:45.331+0000] {dag.py:4180} INFO - Setting next_dagrun for monthly_dag to 2024-12-01 00:00:00+00:00, run_after=2025-01-01 00:00:00+00:00
[2025-01-17T06:57:45.564+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/monthly_dependancy.py took 2.007 seconds
[2025-01-17T06:58:16.506+0000] {processor.py:186} INFO - Started process (PID=557) to work on /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T06:58:16.509+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/monthly_dependancy.py for tasks to queue
[2025-01-17T06:58:16.522+0000] {logging_mixin.py:190} INFO - [2025-01-17T06:58:16.521+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T06:58:16.559+0000] {processor.py:925} INFO - DAG(s) 'monthly_dag' retrieved from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T06:58:16.629+0000] {logging_mixin.py:190} INFO - [2025-01-17T06:58:16.628+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-17T06:58:16.694+0000] {logging_mixin.py:190} INFO - [2025-01-17T06:58:16.694+0000] {dag.py:4180} INFO - Setting next_dagrun for monthly_dag to 2024-12-01 00:00:00+00:00, run_after=2025-01-01 00:00:00+00:00
[2025-01-17T06:58:16.746+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/monthly_dependancy.py took 0.262 seconds
[2025-01-17T07:03:35.825+0000] {processor.py:186} INFO - Started process (PID=588) to work on /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T07:03:36.077+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/monthly_dependancy.py for tasks to queue
[2025-01-17T07:03:36.702+0000] {logging_mixin.py:190} INFO - [2025-01-17T07:03:36.548+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T07:03:43.779+0000] {processor.py:925} INFO - DAG(s) 'monthly_dag' retrieved from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T07:09:48.689+0000] {processor.py:186} INFO - Started process (PID=615) to work on /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T07:09:49.342+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/monthly_dependancy.py for tasks to queue
[2025-01-17T07:09:50.951+0000] {logging_mixin.py:190} INFO - [2025-01-17T07:09:50.369+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/monthly_dependancy.py
[2025-01-17T07:10:08.997+0000] {processor.py:925} INFO - DAG(s) 'monthly_dag' retrieved from /opt/airflow/dags/monthly_dependancy.py
